version: '3.9'
services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "${BACKEND_PROD_PORT:-5000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PROD_PORT:-8080}:80"
    depends_on:
      - backend-prod
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
