version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_DEV_PORT:-5001}:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      PORT: 5000
    command: npm start
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_DEV_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    command: npm exec vite -- --host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
