services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_DEV_PORT:-3000}:3000"
    volumes:
      # Nur /src und index.html mounten für hot reload, nicht ganzes /app
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_DEV_PORT:-5001}:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "${BACKEND_PROD_PORT:-5000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PROD_PORT:-8080}:80"
    depends_on:
      - backend-prod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
