services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      # Nur src und essentielle Files mounten, um node_modules Konflikte zu vermeiden
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      # Backend darf komplett gemounted werden
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
